[2025-07-27T20:01:32.874+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-27T20:01:32.913+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_drift_monitoring.check_drift manual__2025-07-27T20:01:26.248868+00:00 [queued]>
[2025-07-27T20:01:32.922+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_drift_monitoring.check_drift manual__2025-07-27T20:01:26.248868+00:00 [queued]>
[2025-07-27T20:01:32.956+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-07-27T20:01:32.975+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): check_drift> on 2025-07-27 20:01:26.248868+00:00
[2025-07-27T20:01:32.990+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_drift_monitoring', 'check_drift', 'manual__2025-07-27T20:01:26.248868+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/drift_monitoring.py', '--cfg-path', '/tmp/tmp10chtlfc']
[2025-07-27T20:01:32.992+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=666) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-27T20:01:32.994+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask check_drift
[2025-07-27T20:01:32.994+0000] {standard_task_runner.py:63} INFO - Started process 675 to run task
[2025-07-27T20:01:33.014+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-27T20:01:33.061+0000] {task_command.py:426} INFO - Running <TaskInstance: data_drift_monitoring.check_drift manual__2025-07-27T20:01:26.248868+00:00 [running]> on host f9a2821ac4f4
[2025-07-27T20:01:33.178+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops' AIRFLOW_CTX_DAG_ID='data_drift_monitoring' AIRFLOW_CTX_TASK_ID='check_drift' AIRFLOW_CTX_EXECUTION_DATE='2025-07-27T20:01:26.248868+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-27T20:01:26.248868+00:00'
[2025-07-27T20:01:33.180+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-27T20:01:33.202+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-07-27T20:01:33.203+0000] {drift_monitoring.py:51} INFO - Execution date: 2025-07-27 20:01:26.248868+00:00
[2025-07-27T20:01:33.204+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-27T20:01:33.204+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/drift_monitoring.py", line 53, in check_drift
    hour_str = exec_date.strftime("%H") - 2
               ~~~~~~~~~~~~~~~~~~~~~~~~~^~~
TypeError: unsupported operand type(s) for -: 'str' and 'int'
[2025-07-27T20:01:33.221+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=data_drift_monitoring, task_id=check_drift, execution_date=20250727T200126, start_date=20250727T200132, end_date=20250727T200133
[2025-07-27T20:01:33.270+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task check_drift (unsupported operand type(s) for -: 'str' and 'int'; 675)
[2025-07-27T20:01:33.333+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-27T20:01:33.356+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-27T20:01:33.395+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
