[2025-07-27T20:01:29.133+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-27T20:01:29.172+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_drift_monitoring.check_drift scheduled__2025-07-27T19:00:00+00:00 [queued]>
[2025-07-27T20:01:29.181+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_drift_monitoring.check_drift scheduled__2025-07-27T19:00:00+00:00 [queued]>
[2025-07-27T20:01:29.214+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-07-27T20:01:29.231+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): check_drift> on 2025-07-27 19:00:00+00:00
[2025-07-27T20:01:29.246+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=663) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-27T20:01:29.245+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_drift_monitoring', 'check_drift', 'scheduled__2025-07-27T19:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/drift_monitoring.py', '--cfg-path', '/tmp/tmpme5yk9x7']
[2025-07-27T20:01:29.247+0000] {standard_task_runner.py:63} INFO - Started process 665 to run task
[2025-07-27T20:01:29.248+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask check_drift
[2025-07-27T20:01:29.267+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-27T20:01:29.316+0000] {task_command.py:426} INFO - Running <TaskInstance: data_drift_monitoring.check_drift scheduled__2025-07-27T19:00:00+00:00 [running]> on host f9a2821ac4f4
[2025-07-27T20:01:29.498+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops' AIRFLOW_CTX_DAG_ID='data_drift_monitoring' AIRFLOW_CTX_TASK_ID='check_drift' AIRFLOW_CTX_EXECUTION_DATE='2025-07-27T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-27T19:00:00+00:00'
[2025-07-27T20:01:29.500+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-27T20:01:29.523+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-07-27T20:01:29.524+0000] {drift_monitoring.py:51} INFO - Execution date: 2025-07-27 19:00:00+00:00
[2025-07-27T20:01:29.525+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-27T20:01:29.526+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/drift_monitoring.py", line 53, in check_drift
    hour_str = exec_date.strftime("%H") - 2
               ~~~~~~~~~~~~~~~~~~~~~~~~~^~~
TypeError: unsupported operand type(s) for -: 'str' and 'int'
[2025-07-27T20:01:29.545+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=data_drift_monitoring, task_id=check_drift, execution_date=20250727T190000, start_date=20250727T200129, end_date=20250727T200129
[2025-07-27T20:01:29.562+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task check_drift (unsupported operand type(s) for -: 'str' and 'int'; 665)
[2025-07-27T20:01:29.589+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-27T20:01:29.612+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-27T20:01:29.615+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
