[2025-07-27T19:52:03.660+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-27T19:52:03.704+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_drift_monitoring.check_drift manual__2025-07-27T19:51:55.489990+00:00 [queued]>
[2025-07-27T19:52:03.713+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_drift_monitoring.check_drift manual__2025-07-27T19:51:55.489990+00:00 [queued]>
[2025-07-27T19:52:03.747+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-07-27T19:52:03.767+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): check_drift> on 2025-07-27 19:51:55.489990+00:00
[2025-07-27T19:52:03.784+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=779) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-27T19:52:03.781+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_drift_monitoring', 'check_drift', 'manual__2025-07-27T19:51:55.489990+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/drift_monitoring.py', '--cfg-path', '/tmp/tmprzc_iai5']
[2025-07-27T19:52:03.785+0000] {standard_task_runner.py:63} INFO - Started process 781 to run task
[2025-07-27T19:52:03.786+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask check_drift
[2025-07-27T19:52:03.811+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-27T19:52:03.862+0000] {task_command.py:426} INFO - Running <TaskInstance: data_drift_monitoring.check_drift manual__2025-07-27T19:51:55.489990+00:00 [running]> on host ad1b488300d1
[2025-07-27T19:52:04.002+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops' AIRFLOW_CTX_DAG_ID='data_drift_monitoring' AIRFLOW_CTX_TASK_ID='check_drift' AIRFLOW_CTX_EXECUTION_DATE='2025-07-27T19:51:55.489990+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-27T19:51:55.489990+00:00'
[2025-07-27T19:52:04.004+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-27T19:52:04.020+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-07-27T19:52:04.021+0000] {drift_monitoring.py:50} INFO - Execution date: 2025-07-27 19:51:55.489990+00:00
[2025-07-27T19:52:04.023+0000] {drift_monitoring.py:58} INFO - üîç T√©l√©chargement de features/date=2025-07-27/hour=19/features.parquet et targets/date=2025-07-27/hour=19/target.parquet
[2025-07-27T19:52:04.048+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-27T19:52:04.049+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/drift_monitoring.py", line 60, in check_drift
    obj_features = s3_client.get_object(Bucket=BUCKET_NAME, Key=key_features)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[2025-07-27T19:52:04.068+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=data_drift_monitoring, task_id=check_drift, execution_date=20250727T195155, start_date=20250727T195203, end_date=20250727T195204
[2025-07-27T19:52:04.114+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task check_drift (An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.; 781)
[2025-07-27T19:52:04.137+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-27T19:52:04.158+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-27T19:52:04.162+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
